version: 2

sources:
  - name: sources
    database: northwind
    schema: public
    tables:
      - name: categories
      - name: products
      - name: suplliers
      - name: employees
      - name: order_details
      - name: customers
      - name: orders
      - name: shippers
